### ISSUE TITLE
I made a syntax error, but it didn't got refused.

### ISSUE THREAD

**Issue by Peetz0r** [revspace/revbank#7]
I did this incorrect thing:

````2018-08-10_08:21:37 PROMPT Product ID, amount or command >> bapao 2x Peetz0r
2018-08-10_08:21:37 CHECKOUT 233882097     Peetz0r      LOSE EUR  1.00  # Bapao
2018-08-10_08:21:37 CHECKOUT 233882097     Peetz0r           EUR  0.00  # Next product repeated 2 times
2018-08-10_08:21:37 CHECKOUT 233882097     Peetz0r      LOSE EUR  1.00  TOTAL
2018-08-10_08:21:37 BALANCE 233882097 Peetz0r had +9.96, lost 1, now has +8.96
````
So instead of either doing what I wanted or not doing anything and printing an error it, it processed an transaction and created a line with a missing column (no GAIN or LOSE).

**Comment by emansom** [comment]
Perl :ok_hand:

**Comment by Juerd** [comment]
The column isn't missing, but left blank because it is not relevant for an amount of 0.00.

As for "doing what you wanted": `bapao 2x` indeed doesn't do what you want, but it does do something else. It clearly prints that the *next* product will be repeated. To get what you wanted (repeat the *previous* product, you'd type either `2 * bapao` or `bapao * 2`. The `*` operator can also be spelled `x`, and whitespace between the operator and the number is optional.

The transaction was incomplete, but because finishing the transaction is done by one plugin (`user`) and repetition is done by another (`repeat`, which is kind of a hack), it just kept the repetition operation that was on the stack instead of demanding further input.

I'm keeping this issue open because I can't think of an elegant solution. It is, however, not a big deal, as long as people actually read what's on the screen...
